workflows:
  ios-simulator-workflow:
    name: iOS Simulator Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - SECRETS
        
    scripts:
      - name: Clean & get Flutter packages
        script: |
          flutter clean
          flutter pub get
          
      - name: Create .env file from SECRETS
        script: |
          printf "%s\n" "$DOTENV_CONTENT" > .env
          echo "Verification: First 3 lines of .env"
          head -n 3 .env
          
      - name: Clean & install CocoaPods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod cache clean --all
          pod deintegrate
          pod repo update --verbose
          pod update FirebaseAnalytics
          pod install
          cd ..
          
      - name: Clean Flutter artifacts
        script: |
          flutter clean
          flutter pub get
          
      - name: Build for iOS Simulator
        script: |
          flutter build ios --debug \
            --no-codesign \
            --simulator

    artifacts:
      - build/ios/iphonesimulator/*.app
